{{- if .Values.initialJob.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-chart.fullname" . }}
  annotations:
    argocd.argoproj.io/hook: PreSync
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ include "api-chart.fullname" . }}
    job: {{ .Values.application.name }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  created_at: {{ now }}
{{- end }}
