{{- if or .Values.secrets.keys .Values.datadog.enabled (and .Values.autoscaling.enabled .Values.autoscaling.azureServiceBus.connectionFromEnv )}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "api-chart.fullname" . }}
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: {{ .Values.secrets.secretStore.name }}
    kind: {{ .Values.secrets.secretStore.kind }}
  target:
    name: {{ include "api-chart.fullname" . }}
  data:
  {{- if .Values.secrets.keys }}
  {{- range .Values.secrets.keys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.secrets.kv }}/secrets/{{ $.Values.secrets.path }}
        property: {{ . }}
  {{- end }}
  {{- end }}
  {{- if .Values.datadog.enabled }}
    - secretKey: datadogApiKey
      remoteRef:
        key: {{ $.Values.secrets.kv }}/secrets/datadog
        property: api-key
    - secretKey: datadogAppKey
      remoteRef:
        key: {{ $.Values.secrets.kv }}/secrets/datadog
        property: app-key
  {{- end }}
  {{- if and .Values.autoscaling.enabled .Values.autoscaling.azureServiceBus.connectionFromEnv }}
    - secretKey: SERVICEBUS_CONNECTIONSTRING
      remoteRef:
        key: {{ $.Values.secrets.kv }}/secrets/{{ $.Values.secrets.path }}
        property: SERVICEBUS_CONNECTIONSTRING
  {{- end }}
{{- end }}
