{{- if .Values.ingressExternal.enabled }}
{{- $fullName := include "api-chart.fullname" . -}}
{{- $svcPort := .Values.containerPort -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{ end }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    {{- if semverCompare "<1.19-0" $.Capabilities.KubeVersion.GitVersion }}
    kubernetes.io/ingress.class: "{{ .Values.ingressExternal.class }}"
    {{- end }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
  ingressClassName: {{ .Values.ingressExternal.class }}
  {{- end }}
  {{- if not .Values.ingress.tls }}
  tls: []
  {{- else }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingressExternal.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-stable
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-stable
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
