apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "api-chart.fullname" . }}
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
    {{- if .Values.datadog.enabled }}
    tags.datadoghq.com/env: {{ .Values.application.environment }}
    tags.datadoghq.com/service: {{ .Values.application.name }}
    tags.datadoghq.com/version: "{{ .Values.image.tag }}"
    {{- end }}
    app: {{ include "api-chart.fullname" . }}
    {{- with .Values.labels }}
          {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    canary:
      canaryService: {{ include "api-chart.fullname" . }}-canary
      stableService: {{ include "api-chart.fullname" . }}-stable
      #trafficRouting:
        #nginx:
          #stableIngress: {{ include "api-chart.fullname" . }}
      {{- if .Values.steps }}
      steps:
      {{- range $k, $v := .Values.steps }}
        {{- range $k2, $v2 := $v }}
         - {{ $k2 }}: {{ $v2 }}
        {{- end }}
      {{- end }}
      {{- end }}
  selector:
    matchLabels:
      app: {{ include "api-chart.fullname" . }}
  template:
    metadata:
      annotations:
        {{- with .Values.annotations }}
              {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.datadog.enabled }}
        {{- if .Values.datadog.logs.enabled }}
        "ad.datadoghq.com/{{ .Values.application.name }}.logs": '[{"source":"{{ .Values.application.language }}","service":"{{ .Values.application.name }}"}]'
        {{- end }}
        {{- if and (.Values.github.lastCommitSha) (.Values.github.repositoryUrl) }}
        "ad.datadoghq.com/{{ .Values.application.name }}.tags": '{"git.commit.sha": "{{ .Values.github.lastCommitSha }}", "git.repository_url": "{{ .Values.github.repositoryUrl }}", "project": "{{ .Values.labels.project }}", "repository": "{{ .Values.labels.repository }}", "support": "{{ .Values.labels.support }}", "owner": "{{ .Values.labels.owner }}", "cost-center": "{{ index .Values.labels "cost-center" }}", "github-org": "{{ index .Values.labels "github-org" }}", "github-repo": "{{ index .Values.labels "github-repo" }}"}'
        {{- else }}
        "ad.datadoghq.com/{{ .Values.application.name }}.tags": '{"project": "{{ .Values.labels.project }}", "repository": "{{ .Values.labels.repository }}", "support": "{{ .Values.labels.support }}", "owner": "{{ .Values.labels.owner }}", "cost-center": "{{ index .Values.labels "cost-center" }}, "github-org": "{{ index .Values.labels "github-org" }}", "github-repo": "{{ index .Values.labels "github-repo" }}""}'
        {{- end }}
        {{- if and .Values.datadog.apm.enabled .Values.datadog.apm.injection.enabled .Values.datadog.apm.injection.libVersion }}
        admission.datadoghq.com/{{ .Values.datadog.apm.injection.language }}-lib.version: "{{ .Values.datadog.apm.injection.libVersion }}"
        {{- end }}
        {{- end }}
      labels:
        {{- if .Values.datadog.enabled }}
        tags.datadoghq.com/env: {{ .Values.application.environment }}
        tags.datadoghq.com/service: {{ .Values.application.name }}
        tags.datadoghq.com/version: "{{ .Values.image.tag }}"
        {{- if and .Values.datadog.apm.enabled .Values.datadog.apm.injection.enabled .Values.datadog.apm.injection.libVersion }}
        admission.datadoghq.com/enabled: "true"
        admission.datadoghq.com/config.mode: "hostip"
        {{- end }}
        {{- end }}
        {{- if .Values.cloudProviders.azure.enabled }}
        azure.workload.identity/use: "true"
        {{- end }}
        app: {{ include "api-chart.fullname" . }}
        {{- with .Values.labels }}
              {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                - {{ include "api-chart.fullname" . }}
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                - {{ include "api-chart.fullname" . }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- with .Values.tolerations }}
              {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- with .Values.nodeSelector }}
              {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.cloudProviders.aws.karpenter.enabled }}
        {{- if .Values.cloudProviders.aws.karpenter.capacityType }}
        karpenter.sh/capacity-type: {{ .Values.cloudProviders.aws.karpenter.capacityType }}
        {{- else }}
        karpenter.sh/capacity-type: spot
        {{- end }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ include "api-chart.fullname" . }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        runAsNonRoot: true
      containers:
        - name: {{ .Values.application.name }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.autoscaling.kafka.tls }}
            - name: KAFKA_TLS
              value: "enable"
            {{- end }}
            {{- if .Values.autoscaling.kafka.sasl }}
            - name: KAFKA_SASL
              value: {{ .Values.autoscaling.kafka.sasl }}
            {{- end }}
            {{- if .Values.datadog.enabled }}
            {{- if not .Values.datadog.apm.enabled }}
            - name: DD_TRACE_ENABLED
              value: "false"
            {{- end }}
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{- if .Values.datadog.otlp.enabled }}
            - name: OTEL_EXPORTER_OTLP_GRPC_ENDPOINT
              value: "$(DD_AGENT_HOST):4317"
            - name: OTEL_EXPORTER_OTLP_HTTP_ENDPOINT
              value: "http://$(DD_AGENT_HOST):4318"
            {{- end }}
            {{- end }}
            {{- if .Values.envs}}
            {{- range $key, $value := .Values.envs }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- end }}
            {{- if .Values.jsonEnvs }}
            {{- range $key, $value := .Values.jsonEnvs }}
            - name: {{ $key }}
              value: {{ $value | toJson |  quote }}
            {{- end }}
            {{- end }}
            {{- if and .Values.secrets.envVarEnabled .Values.secrets.keys }}
              {{- range .Values.secrets.keys }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-chart.fullname" $ }}
                  key: {{ . }}
              {{- end }}
            {{- end }}
            {{- if and .Values.autoscaling.enabled .Values.autoscaling.azureServiceBus.connectionFromEnv }}
            - name: SERVICEBUS_CONNECTIONSTRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-chart.fullname" $ }}
                  key: SERVICEBUS_CONNECTIONSTRING
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if .Values.healthcheck.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthcheck.livenessProbe.path }}
              port: http
            failureThreshold: {{ .Values.healthcheck.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.healthcheck.livenessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.healthcheck.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.healthcheck.livenessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.healthcheck.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheck.readinessProbe.path }}
              port: http
            failureThreshold: {{ .Values.healthcheck.readinessProbe.failureThreshold }}
            periodSeconds: {{ .Values.healthcheck.readinessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.healthcheck.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.healthcheck.readinessProbe.timeoutSeconds }}
          {{- end }}
          resources:
            limits:
              memory: {{ .Values.resources.memory }}
            requests:
              memory: {{ .Values.resources.memory }}
              cpu: {{ .Values.resources.cpu }}
          {{- if .Values.command }}
          {{- with .Values.command }}
          command:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.args }}
          {{- with .Values.args }}
          args:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- end }}
        {{- range $sidecar := .Values.sidecars }}
        {{- if $sidecar.enabled }}
        - name: {{ $sidecar.name }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          image: "{{ $sidecar.image }}"
          {{- if $sidecar.command }}
          {{- with $sidecar.command }}
          command:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- end }}
          {{- if $sidecar.args }}
          {{- with $sidecar.args }}
          args:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          {{- if $sidecar.containerPort }}
          ports:
            - name: http
              containerPort: {{ $sidecar.containerPort }}
              protocol: TCP
          {{- end }}
          env:
            {{- if $sidecar.envs}}
            {{- range $key, $value := $sidecar.envs }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- end }}
            {{- if  $sidecar.secrets }}
            {{- range $sidecar.secrets }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-chart.fullname" $ }}
                  key: {{ . }}
            {{- end }}
            {{- end }}
          resources:
            limits:
              memory: {{ $sidecar.resources.memory }}
            requests:
              memory: {{ $sidecar.resources.memory }}
              cpu: {{ $sidecar.resources.cpu }}
        {{- end }}
        {{- end }}
          volumeMounts:
          {{- if .Values.secrets.keys }}
          - name: secrets
            mountPath: /secrets
            readOnly: true
          {{- end }}
      volumes:
      {{- if .Values.secrets.keys }}
      - name: secrets
        secret:
          defaultMode: 420
          secretName: {{ include "api-chart.fullname" . }}
      {{- end }}
