apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-chart.fullname" . }}-stable
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "api-chart.fullname" . }}
