apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api-chart.fullname" . }}
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
    {{- with .Values.labels }}
          {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    {{- if and .Values.cloudProviders.aws.enabled .Values.cloudProviders.aws.roleArn }}
    eks.amazonaws.com/role-arn: "{{ .Values.cloudProviders.aws.roleArn }}"
    {{- end }}
    {{- if .Values.cloudProviders.azure.enabled }}
    {{- if and .Values.cloudProviders.azure.workloadIdentity.clientId .Values.cloudProviders.azure.workloadIdentity.tenantId }}
    azure.workload.identity/client-id: {{ .Values.cloudProviders.azure.workloadIdentity.clientId }}
    azure.workload.identity/tenant-id: {{ .Values.cloudProviders.azure.workloadIdentity.tenantId }}
    {{- end }}
    {{- if .Values.cloudProviders.azure.workloadIdentity.serviceAccountTokenExpiration }}
    azure.workload.identity/service-account-token-expiration: {{ .Values.cloudProviders.azure.workloadIdentity.serviceAccountTokenExpiration }}
    {{- end }}
    {{- end }}
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if and .Values.cloudProviders.azure.enabled .Values.cloudProviders.azure.imagePullSecrets.name }}
imagePullSecrets:
- name: {{ .Values.cloudProviders.azure.imagePullSecrets.name }}
{{- end }}
